name: Check MCAST cancelled lectures

on:
  schedule:
    # Runs at 05:30 UTC daily (== 07:30 Malta currently while DST is active)
    - cron: '0 5 * * *'
  workflow_dispatch: {}

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run checker
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          TO_EMAIL: ${{ secrets.TO_EMAIL }}
          CLASS_NAME: ${{ secrets.CLASS_NAME }}
          FUZZY_THRESHOLD: ${{ secrets.FUZZY_THRESHOLD }}
          TARGET_URL: ${{ secrets.TARGET_URL }}
          STATE_FILE: /tmp/mcast_last_notified.txt
        run: |
          python check_cancellations.py
